version: '3.7'

services:
  database:
    image: mysql
    container_name: dev_blog
    restart: always
    volumes:
      - pgdata:/var/lib/mysql
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}

volumes:
  pgdata:
    driver: local
